# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'Ludesco' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  pod 'Firebase/Messaging'

  # Pods for Ludesco
  pod 'react-native-add-calendar-event', :path => '../node_modules/react-native-add-calendar-event'

  target 'LudescoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
