# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'Ludesco' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  pod 'Firebase/Messaging', '4.0.0'

  pod 'react-native-maps', :path => '../node_modules/react-native-maps'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  target 'LudescoTests' do
    # Pods for testing
  end

end
